### ISSUE TITLE
Make new issue

### ISSUE THREAD

**Issue by OlegsLaG** [wmc-olegs/repo#1]
New comment
``<span>Test code</span>``

**Comment by wmc-olegs** [comment]
[notEmptyTextDoc.txt](https://github.com/wmc-olegs/repo/files/1825229/notEmptyTextDoc.txt)
This text file is not empty

**Comment by OlegsLaG** [comment]
[notEmptyTextDoc.txt](https://github.com/wmc-olegs/repo/files/1825232/notEmptyTextDoc.txt)
